# use prebuild go image with indonesia timezone
FROM dimaskiddo/alpine:go-1.13

# set base path
WORKDIR $GOPATH/src/github.com/tobapramudia/tkpd-demo

# copy project to workspace
COPY . ./

# get dependencies library
RUN go get -v

# reset workspace
WORKDIR $GOPATH

# optional, remove the project
ONBUILD RUN rm -rf $GOPATH/src/github.com/tobapramudia